name: Deploy to Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure-credentials.json
          az login --service-principal --username $(jq -r .clientId azure-credentials.json) \
                   --password $(jq -r .clientSecret azure-credentials.json) \
                   --tenant $(jq -r .tenantId azure-credentials.json)

      - name: Deploy to Azure Functions
        run: |
          zip -r functionapp.zip .
          az functionapp deployment source config-zip \
            --resource-group YOUR_RESOURCE_GROUP \
            --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
            --src functionapp.zip
